services:
  spring:
    container_name: spring
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env.prod
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}

  postgres:
    image: postgres:15
    container_name: postgres
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
    ports:
      - "5433:5432"
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: hyn
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-exporter:
    container_name: postgres-exporter
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    env_file:
      - .env.prod
    environment:
      DATA_SOURCE_NAME: "postgresql://${DATASOURCE_USERNAME}:${DATASOURCE_PASSWORD}@postgres:5432/hyn?sslmode=disable"
    depends_on:
      - postgres

volumes:
  postgres_data:
