services:
  postgres:
    image: postgres:15
    container_name: postgres-local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hyn
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data_local:/data

volumes:
  postgres_data_local:
  redis_data_local: