TRUNCATE TABLE city CASCADE;
TRUNCATE TABLE country CASCADE;

-- 나라 데이터 삽입
INSERT INTO country (country_id, name, code)
VALUES (1, 'South Korea', 'KR'),
       (2, 'United States', 'US'),
       (3, 'United Kingdom', 'GB'),
       (4, 'France', 'FR'),
       (5, 'Germany', 'DE'),
       (6, 'Japan', 'JP'),
       (7, 'China', 'CN'),
       (8, 'India', 'IN'),
       (9, 'Australia', 'AU'),
       (10, 'Canada', 'CA'),
       (11, 'Italy', 'IT'),
       (12, 'Spain', 'ES'),
       (13, 'Brazil', 'BR'),
       (14, 'Mexico', 'MX'),
       (15, 'Russia', 'RU'),
       (16, 'South Africa', 'ZA'),
       (17, 'Argentina', 'AR'),
       (18, 'New Zealand', 'NZ'),
       (19, 'Indonesia', 'ID'),
       (20, 'Thailand', 'TH'),
       (21, 'Turkey', 'TR'),
       (22, 'Egypt', 'EG'),
       (23, 'Saudi Arabia', 'SA'),
       (24, 'Vietnam', 'VN'),
       (25, 'Malaysia', 'MY');

-- 도시 데이터 삽입
INSERT INTO city (city_id, name, country_id)
VALUES (1, 'Seoul', 1),
       (2, 'Busan', 1),
       (3, 'New York', 2),
       (4, 'Los Angeles', 2),
       (5, 'Chicago', 2),
       (6, 'London', 3),
       (7, 'Manchester', 3),
       (8, 'Paris', 4),
       (9, 'Lyon', 4),
       (10, 'Berlin', 5),
       (11, 'Munich', 5),
       (12, 'Tokyo', 6),
       (13, 'Osaka', 6),
       (14, 'Beijing', 7),
       (15, 'Shanghai', 7),
       (16, 'Mumbai', 8),
       (17, 'Delhi', 8),
       (18, 'Sydney', 9),
       (19, 'Melbourne', 9),
       (20, 'Toronto', 10),
       (21, 'Vancouver', 10),
       (22, 'Rome', 11),
       (23, 'Milan', 11),
       (24, 'Madrid', 12),
       (25, 'Barcelona', 12),
       (26, 'Rio de Janeiro', 13),
       (27, 'São Paulo', 13),
       (28, 'Mexico City', 14),
       (29, 'Guadalajara', 14),
       (30, 'Moscow', 15),
       (31, 'Saint Petersburg', 15),
       (32, 'Cape Town', 16),
       (33, 'Johannesburg', 16),
       (34, 'Buenos Aires', 17),
       (35, 'Córdoba', 17),
       (36, 'Auckland', 18),
       (37, 'Wellington', 18),
       (38, 'Jakarta', 19),
       (39, 'Bali', 19),
       (40, 'Bangkok', 20),
       (41, 'Chiang Mai', 20),
       (42, 'Istanbul', 21),
       (43, 'Ankara', 21),
       (44, 'Cairo', 22),
       (45, 'Alexandria', 22),
       (46, 'Riyadh', 23),
       (47, 'Jeddah', 23),
       (48, 'Hanoi', 24),
       (49, 'Ho Chi Minh City', 24),
       (50, 'Kuala Lumpur', 25),
       (51, 'Penang', 25);
