spring:
  profiles:
    active: local

  config:
    import: optional:file:.env[.properties],optional:file:.env.${spring.profiles.active}[.properties]

  # datasource:
  #   url: ${DATASOURCE_URL}
  #   username: ${DATASOURCE_USERNAME}
  #   password: ${DATASOURCE_PASSWORD}

  application:
    name: udong

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  sql:
    init:
      mode: always

social:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}

management:
  endpoints:
    web:
      exposure:
        include: prometheus
